In [77]:
%run functions_murano.ipynb

In [2]:
cadastrarAlunos(file_path)

Preencha o seu DRE: 116192484
Preencha o seu Nome Completo: Aluno teste
Preencha o seu Curso: Medicina
Preencha o seu Gênero (Masculino/Feminino): Masculino
Preencha a sua Data de Nascimento (dd/mm/aaaa): 21/04/1994
Preencha a sua Altura (em metros): 1,84
Preencha o seu Peso (em kilos): 89
Preencha o seu CR acumulado (0,0-10,0): 4
Preencha a sua Quantidade de Créditos Obtidos:
Erro! Tenha certeza que digitou corretamente (ex: 390)
Preencha a sua Quantidade de Créditos Obtidos: 0
Preencha a sua Renda Mensal : 0

,dre,curso,nome,genero,data_de_nascimento,altura,peso,cra,creditos_obtidos,renda
0,116192484,Engenharia,Nren Isasa,Feminino,21/12/1994,1.84,84.0,9.0,4444,4444
1,116192484,Engenharia,Breno Matos,Masculino,21/04/1995,1.84,74.0,9.9,8483,43344
2,116192484,Engenharia,Breno Mato,Masculino,21/04/1995,1.80,74.0,9.0,9,9
3,116192484,Engenharia,Aluno 5,Feminino,5/8/2003,1.20,71.0,8.5,223,300
4,116192484,Engenharia,Aluno 6,Feminino,0/7/2004,1.95,74.0,8.7,138,300
...,...,...,...,...,...,...,...,...,...,...
174,116192484,Medicina,Aluno 176,Feminino,30/0/2001,1.24,53.0,3.1,224,5800
175,116192484,Medicina,Aluno 177,Feminino,25/5/2006,1.14,46.0,5.6,25,4800
176,118489494,Medicina,Aluno Tese,Masculino,21/04/1995,1.84,85.0,9.0,90,4000
177,117193567,Engenharia,Breno Matos,Masculino,21/04/1996,1.85,75.0,9.9,833,4000
178,116192484,Medicina,Aluno Teste,Masculino,21/04/1994,1.84,89.0,4.0,0,0

In [78]:
printStatistics()

A média de idade dos alunos é: 21.7
Temos 79 alunas e 99 alunos

A média de CRA dos homens que fazem engenharia é: 4.5
A média de CRA das mulheres que fazem engenharia é: 5.8

A média de CRA das homens que fazem medicina é: 5.7
A média de CRA das mulheres que fazem medicina é: 3.9

A média de renda da medicina é: 4173.3, com desvio padrão de 2556.6
A média de renda da engenharia é: 5236.4, com desvio padrão de 4545.0